@startuml nombre

class Usuario 
class Numero 
class Mascota{
    -Felicidad felicidad 
    +Pasear ()
}
class Juego{
    -Mascota mascota 
    -Usuario usuario
}
class Felicidad{

}
class Porcentaje{
    -numero numero
    +Incrementar (numero)
    +Disminuir(numero)
}

Porcentaje *-- Numero
Usuario o-- Mascota
Mascota *-- Felicidad
Juego *-- Usuario
Juego *-- Mascota 
Felicidad --|> Porcentaje


@enduml